"""add read flags columns

Revision ID: 00fbc44a7987
Revises: 
Create Date: 2025-06-11 16:33:05.287222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fbc44a7987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read_recruiter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_read_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('is_read_user')
        batch_op.drop_column('is_read_recruiter')

    # ### end Alembic commands ###
