"""Add Block model

Revision ID: 345488959eac
Revises: 3c01a3e3bd50
Create Date: 2025-06-15 16:09:20.807183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345488959eac'
down_revision = '3c01a3e3bd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_block'), type_='unique')
        batch_op.create_unique_constraint('uq_block_pair', ['blocker_id', 'blocked_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block', schema=None) as batch_op:
        batch_op.drop_constraint('uq_block_pair', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_block'), ['blocker_id', 'blocked_id'])

    # ### end Alembic commands ###
