'''Add name, email, picture_path to User

Revision ID: 3c01a3e3bd50
Revises: 0fea6b31c561
Create Date: 2025-06-15 15:36:00.178540

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c01a3e3bd50'
down_revision = '0fea6b31c561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('picture_path', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('picture_path')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
    # ### end Alembic commands ###
