"""Add embedding fields to JobOffer and JobSeekerProfile

Revision ID: 795bdfd5e6ca
Revises: c025d34462bf
Create Date: 2025-06-12 03:22:35.731403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '795bdfd5e6ca'
down_revision = 'c025d34462bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('job_seeker_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_embedding', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_seeker_profile', schema=None) as batch_op:
        batch_op.drop_column('cv_embedding')

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
