"""add brand_color

Revision ID: 92f00fbdee89
Revises: 00fbc44a7987
Create Date: 2025-06-11 18:41:57.668366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f00fbdee89'
down_revision = '00fbc44a7987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('brand_color')

    # ### end Alembic commands ###
