"""articles and news

Revision ID: fa35679ef06c
Revises: b73c046ed926
Create Date: 2025-06-12 00:02:54.147583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa35679ef06c'
down_revision = 'b73c046ed926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_job_offer')
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('required_skills',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('min_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('education_required',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('education_required',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('min_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('required_skills',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    op.create_table('_alembic_tmp_job_offer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('recruiter_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('required_skills', sa.TEXT(), nullable=True),
    sa.Column('min_experience', sa.INTEGER(), nullable=True),
    sa.Column('education_required', sa.VARCHAR(length=120), nullable=True),
    sa.Column('country', sa.VARCHAR(length=80), nullable=False),
    sa.Column('city', sa.VARCHAR(length=80), nullable=False),
    sa.Column('category', sa.VARCHAR(length=40), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
